services:
  - type: web
    name: openmes-web
    runtime: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://openmes-web.onrender.com
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: openmes-db
          property: connectionString
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@openmmes.local
      - key: ADMIN_PASSWORD
        sync: false

databases:
  - name: openmes-db
    plan: free
